Khodam = [
  "Kosong"
  "Pendamping Para Raja"
  "Pendamping Para Ratu dan Putri"
  "Naga"
  "Harimau Putih"
  "Buaya Putih"
  "Bhatara Karang"
  "Sulaiman"
  "Rawa Rontek"
  "Macan Tutul"
  "Nyi Blorong"
  "Stoples Kaca"
  "Honda Verza"
  "Cermin Retak"
]
