Khodam = [
  "Kosong"
  "Pendamping Para Raja"
  "Pendamping Para Ratu dan Putri"
  "Raja Maca"
  "Naga"
  "Harimau Putih"
  "Ular Naga"
  "Buaya Putih"
  "Bhatara Karang"
  "Sulaiman"
  "Rawa Rontek"
  "Macan Tutul"
  "Nyi Blorong"
  "Stoples Kaca"
  "Honda Verza"
  "Cermin Retak"
]
